# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e0ca33cf902315426479ef62e16cf227"
application_url = "https://neighbors-antivirus-flower-acc.trycloudflare.com"
embedded = true
name = "nexgen-localhost"
handle = "nexgen-localhost"

[build]
include_config_on_deploy = true
dev_store_url = "quickstart-65c7cede.myshopify.com"
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_analytics,read_inventory,read_orders,read_pixels,read_product_feeds,read_product_listings,read_products,read_publications,read_purchase_options,read_returns,write_product_feeds,write_product_listings,write_products,write_publications"

[auth]
redirect_urls = [
  "https://neighbors-antivirus-flower-acc.trycloudflare.com/auth/callback",
  "https://neighbors-antivirus-flower-acc.trycloudflare.com/auth/shopify/callback",
  "https://neighbors-antivirus-flower-acc.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
